# Deployment Configuration Template for Autodesk Agents Unified
# This file defines environment-specific deployment configurations

# Development Environment Configuration
development:
  deployment:
    image_tag: "latest"
    scale_replicas: 1
    enable_load_balancer: false
    enable_auto_scaling: false
    health_check_timeout: 120
    rollback_enabled: true
    backup_enabled: true
  
  monitoring:
    prometheus_enabled: true
    grafana_enabled: true
    alertmanager_enabled: false
    log_level: "DEBUG"
    metrics_retention: "7d"
  
  performance:
    target_cpu_percent: 80.0
    target_memory_percent: 85.0
    target_response_time_ms: 5000.0
    concurrent_test_requests: 5
  
  security:
    auth_enabled: false
    cors_enabled: true
    rate_limiting_enabled: false
    security_headers_enabled: true
  
  cache:
    cache_ttl: 1800  # 30 minutes
    max_cache_size: "1GB"
    cleanup_interval: 3600  # 1 hour

# Production Environment Configuration
production:
  deployment:
    image_tag: "${IMAGE_TAG}"
    scale_replicas: 3
    enable_load_balancer: true
    enable_auto_scaling: true
    min_replicas: 2
    max_replicas: 10
    health_check_timeout: 300
    rollback_enabled: true
    backup_enabled: true
    notification_webhook: "${NOTIFICATION_WEBHOOK}"
  
  monitoring:
    prometheus_enabled: true
    grafana_enabled: true
    alertmanager_enabled: true
    log_level: "INFO"
    metrics_retention: "30d"
    alert_channels:
      - slack
      - email
      - pagerduty
  
  performance:
    target_cpu_percent: 70.0
    target_memory_percent: 80.0
    target_response_time_ms: 2000.0
    concurrent_test_requests: 20
    cooldown_period: 300
  
  security:
    auth_enabled: true
    cors_enabled: true
    cors_origins: ["https://autodesk.com", "https://*.autodesk.com"]
    rate_limiting_enabled: true
    rate_limit: "100/minute"
    security_headers_enabled: true
    ssl_enabled: true
  
  cache:
    cache_ttl: 3600  # 1 hour
    max_cache_size: "5GB"
    cleanup_interval: 1800  # 30 minutes
    distributed_cache: true

# Staging Environment Configuration
staging:
  deployment:
    image_tag: "${IMAGE_TAG:-staging}"
    scale_replicas: 2
    enable_load_balancer: true
    enable_auto_scaling: false
    health_check_timeout: 180
    rollback_enabled: true
    backup_enabled: true
  
  monitoring:
    prometheus_enabled: true
    grafana_enabled: true
    alertmanager_enabled: true
    log_level: "INFO"
    metrics_retention: "14d"
  
  performance:
    target_cpu_percent: 75.0
    target_memory_percent: 80.0
    target_response_time_ms: 3000.0
    concurrent_test_requests: 15
  
  security:
    auth_enabled: true
    cors_enabled: true
    rate_limiting_enabled: true
    rate_limit: "200/minute"
    security_headers_enabled: true
  
  cache:
    cache_ttl: 2700  # 45 minutes
    max_cache_size: "2GB"
    cleanup_interval: 2400  # 40 minutes

# Testing Environment Configuration
testing:
  deployment:
    image_tag: "test"
    scale_replicas: 1
    enable_load_balancer: false
    enable_auto_scaling: false
    health_check_timeout: 60
    rollback_enabled: false
    backup_enabled: false
  
  monitoring:
    prometheus_enabled: true
    grafana_enabled: false
    alertmanager_enabled: false
    log_level: "DEBUG"
    metrics_retention: "1d"
  
  performance:
    target_cpu_percent: 90.0
    target_memory_percent: 90.0
    target_response_time_ms: 10000.0
    concurrent_test_requests: 3
  
  security:
    auth_enabled: false
    cors_enabled: true
    rate_limiting_enabled: false
    security_headers_enabled: false
  
  cache:
    cache_ttl: 300  # 5 minutes
    max_cache_size: "100MB"
    cleanup_interval: 600  # 10 minutes

# Common Configuration (inherited by all environments)
common:
  agents:
    model_properties:
      enabled: true
      timeout: 30
      retry_attempts: 3
      tools:
        - "create_index"
        - "list_index_properties"
        - "query_index"
        - "execute_jq_query"
    
    aec_data_model:
      enabled: true
      timeout: 30
      retry_attempts: 3
      vector_store_index: "aec_property_definitions"
      similarity_threshold: 0.7
      max_search_results: 8
      tools:
        - "execute_graphql_query"
        - "get_element_categories"
        - "execute_jq_query"
        - "find_related_property_definitions"
    
    model_derivatives:
      enabled: true
      timeout: 30
      retry_attempts: 3
      database_timeout: 30
      max_query_results: 10000
      connection_pool_size: 10
      tools:
        - "sql_database_toolkit"
  
  aws:
    region: "us-east-1"
    bedrock_model_id: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  
  health_checks:
    startup_probe_delay: 30
    readiness_probe_interval: 10
    liveness_probe_interval: 30
    failure_threshold: 3
  
  logging:
    format: "json"
    include_trace_id: true
    log_requests: true
    log_responses: false  # Don't log response bodies for security
  
  validation:
    required_endpoints:
      - "/health"
      - "/health/agents"
      - "/health/dependencies"
      - "/metrics"
      - "/docs"
    
    required_metrics:
      - "http_requests_total"
      - "http_request_duration_seconds"
      - "agent_requests_total"
      - "agent_processing_duration_seconds"
      - "cache_hits_total"
      - "cache_misses_total"
    
    performance_thresholds:
      max_response_time_ms: 5000
      min_success_rate: 0.95
      max_error_rate: 0.05
    
    security_requirements:
      required_headers:
        - "X-Content-Type-Options"
        - "X-Frame-Options"
        - "X-XSS-Protection"
      
      forbidden_headers:
        - "Server"
        - "X-Powered-By"